cat=['Commenting/Sexual Invites', 'Touching /Groping',
       'Others | Commenting/Sexual Invites | Ogling/Facial Expressions/Staring',
       'Commenting/Sexual Invites | Ogling/Facial Expressions/Staring',
       'Ogling/Facial Expressions/Staring',
       'Commenting/Sexual Invites | Touching /Groping | Ogling/Facial Expressions/Staring',
       'Stalking', 'Others', 'Indecent Exposure/Masturbation in public',
       'Rape/Sexual Assault',
       'Commenting/Sexual Invites | Touching /Groping',
       'Commenting/Sexual Invites | Taking photos without permission | Ogling/Facial Expressions/Staring',
       'Commenting/Sexual Invites | Indecent Exposure/Masturbation in public',
       'Commenting/Sexual Invites | Touching /Groping | Taking photos without permission | Ogling/Facial Expressions/Staring',
       'Touching /Groping | Taking photos without permission',
       'Commenting/Sexual Invites | Touching /Groping | Taking photos without permission',
       'Commenting/Sexual Invites | Taking photos without permission',
       'Commenting/Sexual Invites | Touching /Groping | Indecent Exposure/Masturbation in public | Ogling/Facial Expressions/Staring',
       'Taking photos without permission',
       'Touching /Groping | Taking photos without permission | Ogling/Facial Expressions/Staring',
       'Commenting/Sexual Invites | Indecent Exposure/Masturbation in public | Ogling/Facial Expressions/Staring',
       'Commenting/Sexual Invites | Touching /Groping | Indecent Exposure/Masturbation in public',
       'Others | Commenting/Sexual Invites | Touching /Groping',
       'Chain Snatching/Robbery',
       'Taking photos without permission | Ogling/Facial Expressions/Staring',
       'Touching /Groping | Ogling/Facial Expressions/Staring',
       'Commenting/Sexual Invites | Touching /Groping | Rape/Sexual Assault',
       'Indecent Exposure/Masturbation in public | Ogling/Facial Expressions/Staring',
       'Others | Commenting/Sexual Invites',
       'Commenting/Sexual Invites | Chain Snatching/Robbery',
       'Others | Commenting/Sexual Invites | Chain Snatching/Robbery',
       'Touching /Groping | Indecent Exposure/Masturbation in public',
       'Others | Touching /Groping',
       'Commenting/Sexual Invites | Touching /Groping | Chain Snatching/Robbery',
       'Commenting/Sexual Invites | Touching /Groping | Taking photos without permission | Chain Snatching/Robbery',
       'Touching /Groping | Ogling/Facial Expressions/Staring | Indecent Exposure/Masturbation in public | Others | Commenting/Sexual Invites',
       'Ogling/Facial Expressions/Staring | Chain Snatching/Robbery',
       'Indecent Exposure/Masturbation in public | Ogling/Facial Expressions/Staring | Taking photos without permission | Commenting/Sexual Invites | Touching /Groping',
       'Commenting/Sexual Invites | Rape/Sexual Assault',
       'Ogling/Facial Expressions/Staring | Taking photos without permission | Chain Snatching/Robbery | Touching /Groping | Commenting/Sexual Invites | Indecent Exposure/Masturbation in public | Indecent ',
       'Touching /Groping | Chain Snatching/Robbery',
       'Others | Chain Snatching/Robbery',
       'Commenting/Sexual Invites | Ogling/Facial Expressions/Staring | Chain Snatching/Robbery',
       'Others | Ogling/Facial Expressions/Staring',
       'Commenting/Sexual Invites | Touching /Groping | Chain Snatching/Robbery | Rape/Sexual Assault',
       'Taking photos without permission | Rape/Sexual Assault | Ogling/Facial Expressions/Staring | Commenting/Sexual Invites | Touching /Groping',
       'Others | Touching /Groping | Indecent Exposure/Masturbation in public',
       'Others | Indecent Exposure/Masturbation in public',
       'Others | Commenting/Sexual Invites | Touching /Groping | Ogling/Facial Expressions/Staring',
       'Touching /Groping | Taking photos without permission | Chain Snatching/Robbery',
       'Commenting/Sexual Invites | Touching /Groping | Indecent Exposure/Masturbation in public | Taking photos without permission',
       'Indecent Exposure/Masturbation in public | Taking photos without permission | Chain Snatching/Robbery | Rape/Sexual Assault',
       'Commenting/Sexual Invites | Touching /Groping | Indecent Exposure/Masturbation in public | Chain Snatching/Robbery',
       'Others | Commenting/Sexual Invites | Indecent Exposure/Masturbation in public',
       'Ogling/Facial Expressions/Staring | Rape/Sexual Assault | Chain Snatching/Robbery | Commenting/Sexual Invites | Indecent Exposure/Masturbation in public',
       'Commenting/Sexual Invites | Indecent Exposure/Masturbation in public | Taking photos without permission',
       'Others | Commenting/Sexual Invites | Ogling/Facial Expressions/Staring | Chain Snatching/Robbery',
       'Commenting/Sexual Invites | Indecent Exposure/Masturbation in public | Chain Snatching/Robbery',
       'Others | Touching /Groping | Ogling/Facial Expressions/Staring',
       'Others | Taking photos without permission',
       'Others | Commenting/Sexual Invites | Taking photos without permission | Ogling/Facial Expressions/Staring',
       'Commenting/Sexual Invites | Taking photos without permission | Chain Snatching/Robbery',
       'Taking photos without permission | Chain Snatching/Robbery | Ogling/Facial Expressions/Staring | Commenting/Sexual Invites | Touching /Groping',
       'Commenting/Sexual Invites | Taking photos without permission | Ogling/Facial Expressions/Staring | Chain Snatching/Robbery',
       'Ogling/Facial Expressions/Staring | Indecent Exposure/Masturbation in public | Taking photos without permission | Chain Snatching/Robbery | Commenting/Sexual Invites | Others | Commenting/Sexual ',
       'Taking photos without permission | Ogling/Facial Expressions/Staring | Chain Snatching/Robbery',
       'Others | Rape/Sexual Assault',
       'Chain Snatching/Robbery | Rape/Sexual Assault',
       'Commenting/Sexual Invites | Touching /Groping | Ogling/Facial Expressions/Staring | Stalking',
       'Stalking | Ogling/Facial Expressions/Staring | Chain Snatching/Robbery | Touching /Groping | Commenting/Sexual Invites | Taking photos without permission',
       'Touching /Groping | Ogling/Facial Expressions/Staring | Taking photos without permission | Others | Commenting/Sexual Invites',
       'Commenting/Sexual Invites | Indecent Exposure/Masturbation in public | Taking photos without permission | Ogling/Facial Expressions/Staring',
       'Commenting/Sexual Invites | Indecent Exposure/Masturbation in public | Rape/Sexual Assault',
       'Commenting/Sexual Invites | Touching /Groping | Taking photos without permission | Rape/Sexual Assault',
       'Commenting/Sexual Invites | Touching /Groping | Indecent Exposure/Masturbation in public | Rape/Sexual Assault',
       'Indecent Exposure/Masturbation in public | Taking photos without permission',
       'Indecent Exposure/Masturbation in public | Chain Snatching/Robbery',
       'Commenting/Sexual Invites | Taking photos without permission | Ogling/Facial Expressions/Staring | Stalking',
       'Commenting/Sexual Invites | Touching /Groping | Stalking',
       'Others | Commenting/Sexual Invites | Touching /Groping | Taking photos without permission',
       'Commenting/Sexual Invites | Touching /Groping | Ogling/Facial Expressions/Staring | Chain Snatching/Robbery',
       'Commenting/Sexual Invites | Touching /Groping | Ogling/Facial Expressions/Staring | Rape/Sexual Assault',
       'Ogling/Facial Expressions/Staring | Rape/Sexual Assault | Chain Snatching/Robbery | Commenting/Sexual Invites | Taking photos without permission',
       'Indecent Exposure/Masturbation in public | Rape/Sexual Assault | Taking photos without permission | Commenting/Sexual Invites | Touching /Groping',
       'Commenting/Sexual Invites | Ogling/Facial Expressions/Staring | Stalking',
       'Commenting/Sexual Invites | Stalking',
       'Others | Commenting/Sexual Invites | Touching /Groping | Rape/Sexual Assault',
       'Touching /Groping | Rape/Sexual Assault',
       'Taking photos without permission | Chain Snatching/Robbery | Ogling/Facial Expressions/Staring | Others | Commenting/Sexual Invites',
       'Ogling/Facial Expressions/Staring | Indecent Exposure/Masturbation in public | Taking photos without permission | Rape/Sexual Assault | Commenting/Sexual Invites | Others | Touching /Groping | To',
       'Commenting/Sexual Invites | Ogling/Facial Expressions/Staring | Rape/Sexual Assault',
       'Others | Touching /Groping | Rape/Sexual Assault',
       'Touching /Groping | Ogling/Facial Expressions/Staring | Rape/Sexual Assault',
       'Taking photos without permission | Indecent Exposure/Masturbation in public | Rape/Sexual Assault | Commenting/Sexual Invites | Others | Touching /Groping',
       'Others | Commenting/Sexual Invites | Indecent Exposure/Masturbation in public | Ogling/Facial Expressions/Staring',
       'Others | Commenting/Sexual Invites | Taking photos without permission',
       'Touching /Groping | Indecent Exposure/Masturbation in public | Rape/Sexual Assault',
       'Indecent Exposure/Masturbation in public | Taking photos without permission | Ogling/Facial Expressions/Staring',
       'Commenting/Sexual Invites | Taking photos without permission | Rape/Sexual Assault',
       'Commenting/Sexual Invites | Indecent Exposure/Masturbation in public | Taking photos without permission | Rape/Sexual Assault',
       'Ogling/Facial Expressions/Staring | Stalking',
       'Commenting/Sexual Invites | Taking photos without permission | Stalking',
       'Touching /Groping | Stalking',
       'Touching /Groping | Ogling/Facial Expressions/Staring | Stalking',
       'Indecent Exposure/Masturbation in public | Stalking',
       'Taking photos without permission | Stalking',
       'Others | Ogling/Facial Expressions/Staring | Stalking',
       'Others | Commenting/Sexual Invites | Taking photos without permission | Stalking',
       'Commenting/Sexual Invites | Indecent Exposure/Masturbation in public | Ogling/Facial Expressions/Staring | Stalking',
       'Ogling/Facial Expressions/Staring | Rape/Sexual Assault | Chain Snatching/Robbery | Commenting/Sexual Invites | Touching /Groping',
       'Others | Stalking',
       'Taking photos without permission | Chain Snatching/Robbery',
       'Chain Snatching/Robbery | Ogling/Facial Expressions/Staring | Stalking | Rape/Sexual Assault | Touching /Groping | Commenting/Sexual Invites | Indecent Exposure/Masturbation in public | Inde',
       'Touching /Groping | Indecent Exposure/Masturbation in public | Ogling/Facial Expressions/Staring',
       'Touching /Groping | Ogling/Facial Expressions/Staring | Chain Snatching/Robbery',
       'Stalking | Taking photos without permission | Ogling/Facial Expressions/Staring | Rape/Sexual Assault | Touching /Groping | Commenting/Sexual Invites | Indecent Exposure/Masturbation in public | Indecent Exposure/Ma',
       'Stalking | Ogling/Facial Expressions/Staring | Rape/Sexual Assault | Touching /Groping | Commenting/Sexual Invites | Taking photos without permission',
       'Indecent Exposure/Masturbation in public | Stalking | Ogling/Facial Expressions/Staring | Commenting/Sexual Invites | Touching /Groping',
       'Ogling/Facial Expressions/Staring | Rape/Sexual Assault | Stalking | Commenting/Sexual Invites | Touching /Groping',
       'Online Harassment', 'Human Trafficking', 'Domestic Violence',
       'Physical assault',
       'Ogling/Facial Expressions/Staring | Physical assault | Stalking | Touching /Groping | Indecent Exposure/Masturbation in public',
       'Touching /Groping | Indecent Exposure/Masturbation in public | Ogling/Facial Expressions/Staring | Physical assault',
       'Touching /Groping | Ogling/Facial Expressions/Staring | Stalking | Physical assault',
       'Showing Pornography without consent | Ogling/Facial Expressions/Staring | Stalking',
       'Ogling/Facial Expressions/Staring | Rape/Sexual Assault',
       'Online Harassment | Commenting/Sexual Invites',
       'Touching /Groping | Ogling/Facial Expressions/Staring | Stalking | Chain Snatching/Robbery',
       'Ogling/Facial Expressions/Staring | Physical assault | Stalking | Others | Touching /Groping',
       'Physical assault | Chain Snatching/Robbery',
       'Others | Commenting/Sexual Invites | Stalking | Physical assault',
       'Others | Commenting/Sexual Invites | Showing Pornography without consent',
       'Others | Online Harassment | Stalking',
       'Others | Touching /Groping | Chain Snatching/Robbery',
       'Others | Touching /Groping | Stalking',
       'Touching /Groping | Ogling/Facial Expressions/Staring | Physical assault',
       'Others | Online Harassment',
       'Others | Commenting/Sexual Invites | Ogling/Facial Expressions/Staring | Stalking',
       'Physical assault | Domestic Violence | Rape/Sexual Assault',
       'Touching /Groping | Physical assault',
       'Others | Taking photos without permission | Ogling/Facial Expressions/Staring',
       'Touching /Groping | Ogling/Facial Expressions/Staring | Physical assault | Chain Snatching/Robbery',
       'Ogling/Facial Expressions/Staring | Physical assault | Chain Snatching/Robbery',
       'Taking photos without permission | Stalking | Ogling/Facial Expressions/Staring | Commenting/Sexual Invites | Touching /Groping',
       'Online Harassment | Stalking',
       'Touching /Groping | Stalking | Chain Snatching/Robbery',
       'Physical assault | Rape/Sexual Assault',
       'Stalking | Chain Snatching/Robbery',
       'Taking photos without permission | Ogling/Facial Expressions/Staring | Stalking',
       'Stalking | Physical assault | Chain Snatching/Robbery',
       'Touching /Groping | Indecent Exposure/Masturbation in public | Ogling/Facial Expressions/Staring | Rape/Sexual Assault',
       'Others | Human Trafficking | Indecent Exposure/Masturbation in public | Stalking',
       '', 'Physical assault | Domestic Violence',
       'Online Harassment | Taking photos without permission | Stalking',
       'Human Trafficking | Online Harassment | Rape/Sexual Assault',
       'Showing Pornography without consent | Indecent Exposure/Masturbation in public',
       'Touching /Groping | Stalking | Physical assault',
       'Ogling/Facial Expressions/Staring | Physical assault | Stalking | Commenting/Sexual Invites | Touching /Groping',
       'Online Harassment | Showing Pornography without consent',
       'Others | Commenting/Sexual Invites | Stalking',
       'Commenting/Sexual Invites | Physical assault | Domestic Violence',
       'Commenting/Sexual Invites | Touching /Groping | Physical assault',
       'Stalking | Physical assault | Rape/Sexual Assault',
       'Showing Pornography without consent | Stalking',
       'Others | Ogling/Facial Expressions/Staring | Rape/Sexual Assault',
       'Commenting/Sexual Invites | Stalking | Physical assault',
       'Touching /Groping | Taking photos without permission | Stalking',
       'Stalking | Indecent Exposure/Masturbation in public | Ogling/Facial Expressions/Staring | Physical assault | Commenting/Sexual Invites | Others | Touching /Groping | I',
       'Others | Domestic Violence',
       'Showing Pornography without consent',
       'Online Harassment | Touching /Groping | Ogling/Facial Expressions/Staring | Chain Snatching/Robbery',
       'Commenting/Sexual Invites | Touching /Groping | Taking photos without permission | Stalking',
       'Online Harassment | Taking photos without permission | Stalking | Physical assault',
       'Online Harassment | Commenting/Sexual Invites | Indecent Exposure/Masturbation in public',
       'Domestic Violence | Chain Snatching/Robbery',
       'Online Harassment | Commenting/Sexual Invites | Showing Pornography without consent | Taking photos without permission',
       'Touching /Groping | Physical assault | Rape/Sexual Assault',
       'Others | Physical assault | Rape/Sexual Assault',
       'Showing Pornography without consent | Touching /Groping',
       'Online Harassment | Commenting/Sexual Invites | Showing Pornography without consent',
       'Online Harassment | Taking photos without permission',
       'Online Harassment | Physical assault',
       'Indecent Exposure/Masturbation in public | Ogling/Facial Expressions/Staring | Rape/Sexual Assault',
       'Touching /Groping | Taking photos without permission | Physical assault | Rape/Sexual Assault',
       'Online Harassment | Commenting/Sexual Invites | Taking photos without permission',
       'Indecent Exposure/Masturbation in public | Ogling/Facial Expressions/Staring | Stalking',
       'Commenting/Sexual Invites | Ogling/Facial Expressions/Staring | Stalking | Chain Snatching/Robbery',
       'Others | Showing Pornography without consent',
       'Online Harassment | Indecent Exposure/Masturbation in public',
       'Others | Physical assault',
       'Physical assault | Rape/Sexual Assault | Domestic Violence | Touching /Groping | Taking photos without permission',
       'Commenting/Sexual Invites | Touching /Groping | Domestic Violence',
       'Physical assault | Rape/Sexual Assault | Chain Snatching/Robbery | Touching /Groping | Stalking',
       'Commenting/Sexual Invites | Physical assault | Chain Snatching/Robbery',
       'Commenting/Sexual Invites | Domestic Violence',
       'Human Trafficking | Commenting/Sexual Invites',
       'Ogling/Facial Expressions/Staring | Stalking | Physical assault',
       'Stalking | Ogling/Facial Expressions/Staring | Rape/Sexual Assault | Touching /Groping | Commenting/Sexual Invites | Indecent Exposure/Masturbation in public',
       'Taking photos without permission | Rape/Sexual Assault',
       'Commenting/Sexual Invites | Ogling/Facial Expressions/Staring | Stalking | Physical assault',
       'Touching /Groping | Stalking | Physical assault | Chain Snatching/Robbery',
       'Touching /Groping | Stalking | Physical assault | Rape/Sexual Assault',
       'Online Harassment | Commenting/Sexual Invites | Showing Pornography without consent | Indecent Exposure/Masturbation in public',
       'Touching /Groping | Physical assault | Chain Snatching/Robbery',
       'Commenting/Sexual Invites | Touching /Groping | Ogling/Facial Expressions/Staring | Physical assault',
       'Online Harassment | Commenting/Sexual Invites | Stalking',
       'Touching /Groping | Physical assault | Domestic Violence',
       'Online Harassment | Touching /Groping | Ogling/Facial Expressions/Staring',
       'Commenting/Sexual Invites | Touching /Groping | Stalking | Physical assault',
       'Online Harassment | Showing Pornography without consent | Stalking',
       'Commenting/Sexual Invites | Ogling/Facial Expressions/Staring | Stalking | Rape/Sexual Assault',
       'Physical assault | Taking photos without permission | Ogling/Facial Expressions/Staring | Domestic Violence | Commenting/Sexual Invites | Online Harassment | Touching /Groping | Touching /G',
       'Commenting/Sexual Invites | Taking photos without permission | Ogling/Facial Expressions/Staring | Rape/Sexual Assault',
       'Commenting/Sexual Invites | Showing Pornography without consent',
       'Touching /Groping | Physical assault | Ogling/Facial Expressions/Staring | Human Trafficking | Commenting/Sexual Invites',
       'Stalking | Chain Snatching/Robbery | Physical assault | Commenting/Sexual Invites | Touching /Groping',
       'Online Harassment | Ogling/Facial Expressions/Staring',
       'Touching /Groping | Taking photos without permission | Stalking | Domestic Violence',
       'Stalking | Physical assault | Chain Snatching/Robbery | Rape/Sexual Assault',
       'Commenting/Sexual Invites | Physical assault',
       'Taking photos without permission | Physical assault',
       'Showing Pornography without consent | Rape/Sexual Assault',
       'Others | Taking photos without permission | Stalking',
       'Online Harassment | Rape/Sexual Assault',
       'Ogling/Facial Expressions/Staring | Rape/Sexual Assault | Stalking | Commenting/Sexual Invites | Indecent Exposure/Masturbation in public',
       'Online Harassment | Touching /Groping | Physical assault | Domestic Violence',
       'Ogling/Facial Expressions/Staring | Rape/Sexual Assault | Physical assault | Commenting/Sexual Invites | Touching /Groping',
       'Commenting/Sexual Invites | Touching /Groping | Physical assault | Rape/Sexual Assault',
       'Commenting/Sexual Invites | Indecent Exposure/Masturbation in public | Stalking',
       'Stalking | Physical assault',
       'Stalking | Taking photos without permission | Ogling/Facial Expressions/Staring | Physical assault | Commenting/Sexual Invites | Online Harassment | Touching /Groping | Takin',
       'Stalking | Ogling/Facial Expressions/Staring | Physical assault | Commenting/Sexual Invites | Online Harassment | Touching /Groping',
       'Showing Pornography without consent | Touching /Groping | Indecent Exposure/Masturbation in public',
       'Human Trafficking | Commenting/Sexual Invites | Taking photos without permission | Physical assault',
       'Commenting/Sexual Invites | Ogling/Facial Expressions/Staring | Physical assault',
       'Touching /Groping | Taking photos without permission | Indecent Exposure/Masturbation in public | Commenting/Sexual Invites | Showing Pornography without consent',
       'Indecent Exposure/Masturbation in public | Rape/Sexual Assault',
       'Taking photos without permission | Stalking | Ogling/Facial Expressions/Staring | Online Harassment | Commenting/Sexual Invites',
       'Others | Stalking | Physical assault',
       'Touching /Groping | Taking photos without permission | Ogling/Facial Expressions/Staring | Physical assault',
       'Taking photos without permission | Indecent Exposure/Masturbation in public | Ogling/Facial Expressions/Staring | Showing Pornography without consent | Commenting/Sexual Invites | Touc',
       'Stalking | Rape/Sexual Assault',
       'Commenting/Sexual Invites | Showing Pornography without consent | Ogling/Facial Expressions/Staring',
       'Commenting/Sexual Invites | Touching /Groping | Indecent Exposure/Masturbation in public | Stalking',
       'Indecent Exposure/Masturbation in public | Ogling/Facial Expressions/Staring | Taking photos without permission | Online Harassment | Touching /Groping',
       'Physical assault | Rape/Sexual Assault | Domestic Violence | Commenting/Sexual Invites | Touching /Groping',
       'Commenting/Sexual Invites | Touching /Groping | Stalking | Domestic Violence',
       'Showing Pornography without consent | Taking photos without permission | Stalking',
       'Commenting/Sexual Invites | Showing Pornography without consent | Touching /Groping',
       'Others | Online Harassment | Ogling/Facial Expressions/Staring',
       'Online Harassment | Showing Pornography without consent | Taking photos without permission',
       'Stalking | Chain Snatching/Robbery | Rape/Sexual Assault',
       'Physical assault | Rape/Sexual Assault | Domestic Violence | Showing Pornography without consent | Touching /Groping',
       'Commenting/Sexual Invites | Showing Pornography without consent | Touching /Groping | Ogling/Facial Expressions/Staring',
       'Stalking | Physical assault | Domestic Violence',
       'Domestic Violence | Chain Snatching/Robbery | Rape/Sexual Assault',
       'Domestic Violence | Rape/Sexual Assault | Chain Snatching/Robbery | Stalking | Physical assault',
       'Physical assault | Domestic Violence | Chain Snatching/Robbery',
       'Showing Pornography without consent | Touching /Groping | Rape/Sexual Assault',
       'Touching /Groping | Physical assault | Domestic Violence | Rape/Sexual Assault',
       'Domestic Violence | Rape/Sexual Assault',
       'Others | Online Harassment | Physical assault | Chain Snatching/Robbery',
       'Commenting/Sexual Invites | Showing Pornography without consent | Rape/Sexual Assault',
       'Showing Pornography without consent | Taking photos without permission',
       'Physical assault | Stalking | Domestic Violence | Touching /Groping | Human Trafficking | Ogling/Facial Expressions/Staring',
       'Physical assault | Stalking | Ogling/Facial Expressions/Staring | Domestic Violence | Rape/Sexual Assault | Chain Snatching/Robbery | Rape/Sexual Assa',
       'Stalking | Rape/Sexual Assault | Physical assault | Showing Pornography without consent | Ogling/Facial Expressions/Staring',
       'Physical assault | Stalking | Rape/Sexual Assault | Taking photos without permission | Touching /Groping | Ogling/Facial Expressions/Staring',
       'Online Harassment | Commenting/Sexual Invites | Ogling/Facial Expressions/Staring',
       'Touching /Groping | Domestic Violence | Chain Snatching/Robbery',
       'Online Harassment | Commenting/Sexual Invites | Ogling/Facial Expressions/Staring | Stalking',
       'Commenting/Sexual Invites | Stalking | Chain Snatching/Robbery',
       'Touching /Groping | Indecent Exposure/Masturbation in public | Ogling/Facial Expressions/Staring | Stalking',
       'Touching /Groping | Stalking | Ogling/Facial Expressions/Staring | Commenting/Sexual Invites | Showing Pornography without consent',
       'Indecent Exposure/Masturbation in public | Physical assault | Ogling/Facial Expressions/Staring | Commenting/Sexual Invites | Touching /Groping',
       'Physical assault | Stalking | Rape/Sexual Assault | Indecent Exposure/Masturbation in public | Touching /Groping | Ogling/Facial Expressions/Staring',
       'Indecent Exposure/Masturbation in public | Rape/Sexual Assault | Physical assault | Showing Pornography without consent | Touching /Groping',
       'Touching /Groping | Indecent Exposure/Masturbation in public | Physical assault | Rape/Sexual Assault',
       'Physical assault | Rape/Sexual Assault | Chain Snatching/Robbery | Commenting/Sexual Invites | Touching /Groping',
       'Touching /Groping | Indecent Exposure/Masturbation in public | Taking photos without permission',
       'Showing Pornography without consent | Touching /Groping | Taking photos without permission | Ogling/Facial Expressions/Staring',
       'Stalking | Ogling/Facial Expressions/Staring | Physical assault | Touching /Groping | Commenting/Sexual Invites | Indecent Exposure/Masturbation in public',
       'Ogling/Facial Expressions/Staring | Indecent Exposure/Masturbation in public | Taking photos without permission | Stalking | Commenting/Sexual Invites | Online Harassment | Touching /Groping | To',
       'Ogling/Facial Expressions/Staring | Taking photos without permission | Stalking | Touching /Groping | Online Harassment | Indecent Exposure/Masturbation in public',
       'Others | Showing Pornography without consent | Touching /Groping | Rape/Sexual Assault',
       'Showing Pornography without consent | Taking photos without permission | Touching /Groping | Others | Commenting/Sexual Invites',
       'Touching /Groping | Taking photos without permission | Rape/Sexual Assault',
       'Others | Touching /Groping | Physical assault',
       'Online Harassment | Ogling/Facial Expressions/Staring | Stalking',
       'Taking photos without permission | Stalking | Ogling/Facial Expressions/Staring | Commenting/Sexual Invites | Indecent Exposure/Masturbation in public',
       'Ogling/Facial Expressions/Staring | Physical assault',
       'Showing Pornography without consent | Indecent Exposure/Masturbation in public | Ogling/Facial Expressions/Staring',
       'Touching /Groping | Taking photos without permission | Ogling/Facial Expressions/Staring | Stalking',
       'Domestic Violence | Physical assault | Rape/Sexual Assault | Showing Pornography without consent | Commenting/Sexual Invites | Touching /Groping',
       'Ogling/Facial Expressions/Staring | Rape/Sexual Assault | Physical assault | Touching /Groping | Taking photos without permission',
       'Ogling/Facial Expressions/Staring | Taking photos without permission | Stalking | Showing Pornography without consent | Commenting/Sexual Invites | Touching /Groping',
       'Commenting/Sexual Invites | Showing Pornography without consent | Physical assault',
       'Touching /Groping | Ogling/Facial Expressions/Staring | Physical assault | Rape/Sexual Assault',
       'Showing Pornography without consent | Ogling/Facial Expressions/Staring',
       'Others | Online Harassment | Ogling/Facial Expressions/Staring | Stalking',
       'Commenting/Sexual Invites | Stalking | Physical assault | Rape/Sexual Assault',
       'Online Harassment | Commenting/Sexual Invites | Taking photos without permission | Ogling/Facial Expressions/Staring',
       'Online Harassment | Taking photos without permission | Ogling/Facial Expressions/Staring | Stalking',
       'Taking photos without permission | Rape/Sexual Assault | Physical assault | Commenting/Sexual Invites | Indecent Exposure/Masturbation in public',
       'Commenting/Sexual Invites | Indecent Exposure/Masturbation in public | Physical assault | Rape/Sexual Assault',
       'Others | Touching /Groping | Stalking | Physical assault',
       'Others | Commenting/Sexual Invites | Touching /Groping | Indecent Exposure/Masturbation in public',
       'Touching /Groping | Stalking | Ogling/Facial Expressions/Staring | Others | Commenting/Sexual Invites',
       'Touching /Groping | Stalking | Domestic Violence',
       'Human Trafficking | Touching /Groping | Physical assault',
       'Human Trafficking | Domestic Violence | Rape/Sexual Assault',
       'Stalking | Domestic Violence | Rape/Sexual Assault',
       'Indecent Exposure/Masturbation in public | Chain Snatching/Robbery | Physical assault | Human Trafficking | Touching /Groping',
       'Touching /Groping | Stalking | Rape/Sexual Assault',
       'Others | Physical assault | Chain Snatching/Robbery',
       'Commenting/Sexual Invites | Touching /Groping | Stalking | Rape/Sexual Assault',
       'Human Trafficking | Commenting/Sexual Invites | Touching /Groping | Stalking',
       'Human Trafficking | Touching /Groping | Stalking | Rape/Sexual Assault',
       'Others | Human Trafficking',
       'Others | Commenting/Sexual Invites | Touching /Groping | Stalking',
       'Stalking | Ogling/Facial Expressions/Staring | Physical assault | Touching /Groping | Showing Pornography without consent | Taking photos without permission',
       'Taking photos without permission | Stalking | Physical assault',
       'Taking photos without permission | Physical assault | Ogling/Facial Expressions/Staring | Commenting/Sexual Invites | Touching /Groping',
       'Ogling/Facial Expressions/Staring | Stalking | Chain Snatching/Robbery',
       'Ogling/Facial Expressions/Staring | Stalking | Physical assault | Rape/Sexual Assault',
       'Touching /Groping | Taking photos without permission | Physical assault',
       'Online Harassment | Touching /Groping',
       'Others | Online Harassment | Commenting/Sexual Invites | Touching /Groping',
       'Others | Online Harassment | Commenting/Sexual Invites | Physical assault',
       'Stalking | Domestic Violence',
       'Others | Domestic Violence | Chain Snatching/Robbery',
       'Online Harassment | Commenting/Sexual Invites | Stalking | Rape/Sexual Assault',
       'Others | Online Harassment | Commenting/Sexual Invites | Showing Pornography without consent',
       'Others | Online Harassment | Chain Snatching/Robbery',
       'Others | Commenting/Sexual Invites | Domestic Violence',
       'Others | Taking photos without permission | Rape/Sexual Assault',
       'Commenting/Sexual Invites | Showing Pornography without consent | Touching /Groping | Stalking',
       'Touching /Groping | Stalking | Chain Snatching/Robbery | Rape/Sexual Assault',
       'Taking photos without permission | Stalking | Domestic Violence',
       'Indecent Exposure/Masturbation in public | Taking photos without permission | Ogling/Facial Expressions/Staring | Stalking',
       'Online Harassment | Commenting/Sexual Invites | Touching /Groping',
       'Others | Human Trafficking | Stalking',
       'Others | Stalking | Rape/Sexual Assault',
       'Others | Stalking | Domestic Violence',
       'Human Trafficking | Online Harassment',
       'Human Trafficking | Stalking',
       'Others | Showing Pornography without consent | Taking photos without permission',
       'Taking photos without permission | Rape/Sexual Assault | Stalking | Others | Showing Pornography without consent',
       'Showing Pornography without consent | Touching /Groping | Taking photos without permission',
       'Others | Domestic Violence | Rape/Sexual Assault',
       'Others | Showing Pornography without consent | Taking photos without permission | Stalking',
       'Showing Pornography without consent | Indecent Exposure/Masturbation in public | Taking photos without permission | Stalking',
       'Touching /Groping | Stalking | Taking photos without permission | Others | Showing Pornography without consent',
       'Others | Showing Pornography without consent | Stalking',
       'Others | Touching /Groping | Taking photos without permission | Physical assault',
       'Showing Pornography without consent | Touching /Groping | Taking photos without permission | Stalking',
       'Others | Showing Pornography without consent | Touching /Groping | Stalking',
       'Others | Showing Pornography without consent | Touching /Groping | Taking photos without permission',
       'Showing Pornography without consent | Touching /Groping | Stalking',
       'Online Harassment | Chain Snatching/Robbery',
       'Showing Pornography without consent | Indecent Exposure/Masturbation in public | Rape/Sexual Assault',
       'Human Trafficking | Physical assault',
       'Touching /Groping | Domestic Violence',
       'Online Harassment | Stalking | Physical assault',
       'Taking photos without permission | Ogling/Facial Expressions/Staring | Stalking | Physical assault',
       'Showing Pornography without consent | Touching /Groping | Physical assault | Domestic Violence',
       'Online Harassment | Domestic Violence',
       'Indecent Exposure/Masturbation in public | Ogling/Facial Expressions/Staring | Physical assault | Chain Snatching/Robbery',
       'Ogling/Facial Expressions/Staring | Indecent Exposure/Masturbation in public | Taking photos without permission | Chain Snatching/Robbery | Showing Pornography without consent | Commenting/Sexual Invites | Showing Pornography without con']